#!/usr/bin/env sh
set -eu

# Duration-mode reconnect smoke to guard against "attempted=0" regressions.
DURATION_SMOKE_CONCURRENCY="${DURATION_SMOKE_CONCURRENCY:-256}"
DURATION_SMOKE_DURATION_SECS="${DURATION_SMOKE_DURATION_SECS:-4}"
DURATION_SMOKE_WORKER_START_SPREAD_MS="${DURATION_SMOKE_WORKER_START_SPREAD_MS:-1000}"
DURATION_SMOKE_MIN_RPS="${DURATION_SMOKE_MIN_RPS:-5}"
DURATION_SMOKE_MAX_FAILURE_RATE="${DURATION_SMOKE_MAX_FAILURE_RATE:-0.2}"
DURATION_SMOKE_PROFILE="${DURATION_SMOKE_PROFILE:-fanout}"
DURATION_SMOKE_CONNECT_TIMEOUT_MS="${DURATION_SMOKE_CONNECT_TIMEOUT_MS:-1500}"
DURATION_SMOKE_QUEUE_WAIT_MAX_AGE_MS="${DURATION_SMOKE_QUEUE_WAIT_MAX_AGE_MS:-5000}"

echo "[duration-smoke] running duration-mode reconnect smoke"
echo "[duration-smoke] concurrency=$DURATION_SMOKE_CONCURRENCY duration=${DURATION_SMOKE_DURATION_SECS}s spread_ms=$DURATION_SMOKE_WORKER_START_SPREAD_MS"

SLO_PROFILE="$DURATION_SMOKE_PROFILE" \
SLO_CONCURRENCY="$DURATION_SMOKE_CONCURRENCY" \
SLO_DURATION_SECS="$DURATION_SMOKE_DURATION_SECS" \
SLO_WARMUP=0 \
SLO_WORKER_START_SPREAD_MS="$DURATION_SMOKE_WORKER_START_SPREAD_MS" \
SLO_MIN_RPS="$DURATION_SMOKE_MIN_RPS" \
SLO_MAX_P95_US=0 \
SLO_MAX_FAILURE_RATE="$DURATION_SMOKE_MAX_FAILURE_RATE" \
SLO_CONNECT_TIMEOUT_MS="$DURATION_SMOKE_CONNECT_TIMEOUT_MS" \
SLO_QUEUE_WAIT_MAX_AGE_MS="$DURATION_SMOKE_QUEUE_WAIT_MAX_AGE_MS" \
./scripts/bench_slo_gate.sh

echo "[duration-smoke] passed"
