#!/usr/bin/env sh
set -eu

# Dedicated 1000-session reconnect gate tuned for fan-out regressions.
SLO_CONCURRENCY="${SLO_CONCURRENCY:-1000}"
SLO_DURATION_SECS="${SLO_DURATION_SECS:-15}"
SLO_PAYLOAD_SIZE="${SLO_PAYLOAD_SIZE:-64}"
SLO_WORKER_START_SPREAD_MS="${SLO_WORKER_START_SPREAD_MS:-2000}"
SLO_PROFILE="${SLO_PROFILE:-pssh}"
SLO_MIN_RPS="${SLO_MIN_RPS:-20}"
SLO_MAX_P95_US="${SLO_MAX_P95_US:-350000}"
SLO_MAX_FAILURE_RATE="${SLO_MAX_FAILURE_RATE:-0.02}"

echo "[fanout-1000] running reconnect SLO gate"
echo "[fanout-1000] concurrency=$SLO_CONCURRENCY duration=${SLO_DURATION_SECS}s spread_ms=$SLO_WORKER_START_SPREAD_MS profile=$SLO_PROFILE"

SLO_CONCURRENCY="$SLO_CONCURRENCY" \
SLO_DURATION_SECS="$SLO_DURATION_SECS" \
SLO_PAYLOAD_SIZE="$SLO_PAYLOAD_SIZE" \
SLO_WORKER_START_SPREAD_MS="$SLO_WORKER_START_SPREAD_MS" \
SLO_PROFILE="$SLO_PROFILE" \
SLO_MIN_RPS="$SLO_MIN_RPS" \
SLO_MAX_P95_US="$SLO_MAX_P95_US" \
SLO_MAX_FAILURE_RATE="$SLO_MAX_FAILURE_RATE" \
./scripts/bench_slo_gate.sh

echo "[fanout-1000] gate passed"
