#!/usr/bin/env sh
set -eu

REGRESSION_OPENSSH_KEY_TYPES="${REGRESSION_OPENSSH_KEY_TYPES:-ed25519,rsa,ecdsa}"
REGRESSION_BENCH_CONCURRENCY="${REGRESSION_BENCH_CONCURRENCY:-96}"
REGRESSION_BENCH_REQUESTS="${REGRESSION_BENCH_REQUESTS:-6}"
REGRESSION_BENCH_MIN_RPS="${REGRESSION_BENCH_MIN_RPS:-20}"
REGRESSION_SLO_CONCURRENCY="${REGRESSION_SLO_CONCURRENCY:-64}"
REGRESSION_SLO_DURATION_SECS="${REGRESSION_SLO_DURATION_SECS:-10}"
REGRESSION_SLO_MIN_RPS="${REGRESSION_SLO_MIN_RPS:-10}"
REGRESSION_SLO_MAX_P95_US="${REGRESSION_SLO_MAX_P95_US:-900000}"
REGRESSION_SLO_MAX_FAILURE_RATE="${REGRESSION_SLO_MAX_FAILURE_RATE:-0.05}"
REGRESSION_SLO_MAX_QUEUE_WAIT_AVG_NS="${REGRESSION_SLO_MAX_QUEUE_WAIT_AVG_NS:-100000000}"
REGRESSION_SLO_MAX_QUEUE_WAIT_MAX_NS="${REGRESSION_SLO_MAX_QUEUE_WAIT_MAX_NS:-1000000000}"

echo "[regression] OpenSSH compatibility matrix smoke"
OPENSSH_KEY_TYPES="$REGRESSION_OPENSSH_KEY_TYPES" ./scripts/openssh_compat_smoke.sh

echo "[regression] Reconnect bench smoke gate"
BENCH_CONCURRENCY="$REGRESSION_BENCH_CONCURRENCY" \
BENCH_REQUESTS="$REGRESSION_BENCH_REQUESTS" \
MIN_RPS="$REGRESSION_BENCH_MIN_RPS" \
./scripts/bench_smoke_gate.sh

echo "[regression] Reconnect SLO gate"
SLO_CONCURRENCY="$REGRESSION_SLO_CONCURRENCY" \
SLO_DURATION_SECS="$REGRESSION_SLO_DURATION_SECS" \
SLO_MIN_RPS="$REGRESSION_SLO_MIN_RPS" \
SLO_MAX_P95_US="$REGRESSION_SLO_MAX_P95_US" \
SLO_MAX_FAILURE_RATE="$REGRESSION_SLO_MAX_FAILURE_RATE" \
SLO_MAX_QUEUE_WAIT_AVG_NS="$REGRESSION_SLO_MAX_QUEUE_WAIT_AVG_NS" \
SLO_MAX_QUEUE_WAIT_MAX_NS="$REGRESSION_SLO_MAX_QUEUE_WAIT_MAX_NS" \
./scripts/bench_slo_gate.sh

echo "[regression] all checks passed"
